### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by kraoadori** [google/identity-toolkit-go-client#11]
I want to use [Sourcegraph](https://sourcegraph.com) for identity-toolkit-go-client code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/google/identity-toolkit-go-client. (It should only take 30 seconds.)

Thank you!

**Comment by dereksalama** [comment]
Sourcegraph enabled.
