### ISSUE TITLE
Add a NewWithContext function to the non appengine build

### ISSUE THREAD

**Issue by jonprice** [google/identity-toolkit-go-client#9]
The switch to google.golang.org/appengine means that app engine projects can be be built using the standard go tools, this is useful as goapp dosn't work well with oracle, gocode etc. 

The issue is there is no NewWithContext function on the non appengine build. If this was added GitKit could could be used in app engine projects and use the go tools.

**Comment by dereksalama** [comment]
Thanks for the contribution. We can merge your pull request and close this issue once you sign the CLA.

**Comment by jonprice** [comment]
Google CLA has been submitted for github account jonprice

**Comment by dereksalama** [comment]
Great, your pull request has been merged. Thanks for the contribution!
